spring:
  datasource:
    password: 123456
    username: postgres
    url: jdbc:postgresql://localhost:5432/fornecedor
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
